storage:
  dbPath: /data/db
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.5
systemLog:
  destination: file
  path: /data/db/mongod.log
  logAppend: true
net:
  port: 27018
  bindIpAll: true
security:
  keyFile: /run/mongo-secrets/mongodb-keyfile
replication:
  replSetName: REPLACED_BY_CLI
sharding:
  clusterRole: shardsvr
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
