systemLog:
  destination: file
  path: /tmp/mongos.log
  logAppend: true
net:
  port: 27017
  bindIpAll: true
security:
  keyFile: /run/mongo-secrets/mongodb-keyfile
sharding:
  configDB: cfgReplSet/cfg1:27019,cfg2:27019,cfg3:27019
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
